---
template_storage: local-lvm
alma_image_url: "https://raw.repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
alma_image_filename: "AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
template_search_domain: "local"

# New variable for where to store the downloaded image on the Proxmox host
image_download_path: "/var/lib/vz/template/cache"