---
- name: Ensure necessary packages are installed
  ansible.builtin.dnf:
    name:
      - samba
      - samba-client
      - policycoreutils-python-utils
    state: present
    update_cache: true

- name: Create the Samba group
  ansible.builtin.group:
    name: "{{ samba_group }}"
    state: present

- name: Create the Samba user
  ansible.builtin.user:
    name: "{{ samba_user }}"
    state: present
    shell: /bin/bash
    groups:
      - "{{ samba_sudo_group }}"
      - "{{ samba_group }}"
    append: true

- name: Set Samba password for the user
  ansible.builtin.shell:
    cmd: set -o pipefail && echo -ne '{{ samba_user_password }}\n{{ samba_user_password }}\n' | smbpasswd -s -a {{ samba_user }}
  args:
    executable: /bin/bash
  changed_when: true
  no_log: true

- name: Ensure the Samba share mount point exists
  ansible.builtin.file:
    path: "{{ samba_mount_path }}"
    state: directory
    mode: "0755"

- name: Enable necessary Samba SELinux booleans
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  loop:
    - samba_enable_home_dirs
    - samba_export_all_rw

- name: Get current state of Samba SELinux booleans (for verification)
  ansible.builtin.command: getsebool samba_enable_home_dirs samba_export_all_rw
  changed_when: false

- name: Allow Samba service through the firewall
  ansible.posix.firewalld:
    service: samba
    permanent: true
    state: enabled
    immediate: true

- name: Configure Samba share in smb.conf
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [share]
          comment = Cross-Platform Shared Folder
          path = {{ samba_mount_path }}
          browseable = Yes
          read only = No
          writable = yes
          valid users = @{{ samba_group }}
          write list = @{{ samba_group }}
          inherit permissions = yes

          # Permissions
          create mask = 0660
          directory mask = 0775

          # macOS Compatibility (VFS Objects)
          vfs objects = fruit streams_xattr
          fruit:metadata = stream
          fruit:model = MacSamba
          fruit:veto_appledouble = no
          fruit:nfs_aces = no
          fruit:wipe_intentionally_left_blank_rfork = yes
          fruit:delete_empty_adfiles = yes
          fruit:posix_rename = yes
    state: present
    create: false
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ samba_mount_path }}"
  notify: Restart Samba Services # Notify handler if change is made

- name: Ensure Samba services are enabled and running
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - smb.service
    - nmb.service
