github_runner_version: "2.317.0"
# Used for direct API calls like getting the registration token
github_api_url: "https://api.github.com/repos/hakonskogsrud/serversetup"
# Used for the runner's config.sh script
github_web_url: "https://github.com/hakonskogsrud/serversetup"
github_runner_name: "{{ inventory_hostname }}"
github_runner_labels: "homelab"
github_runner_user: "runner"
github_runner_dir: "/opt/github-runner"
github_pat: "" # GitHub Personal Access Token with 'repo' scope
