---
- name: Ensure the update script directory exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: "0755"

- name: Ensure log file exists with proper permissions
  ansible.builtin.file:
    path: "{{ scheduled_update_log_file }}"
    state: touch
    mode: "0666"
    owner: root
    group: root

- name: Create the update script with logging
  ansible.builtin.template:
    src: scheduled_update.sh.j2
    dest: "/usr/local/bin/{{ scheduled_update_script_name }}.sh"
    mode: "0755"

- name: Add a cron job to run the update script daily as root
  ansible.builtin.cron:
    name: "Daily package updates"
    job: "pushover_token_update='{{ pushover_token_update }}' pushover_user='{{ pushover_user }}' /usr/local/bin/{{ scheduled_update_script_name }}.sh"
    user: root
    weekday: "*"
    hour: "22"
    minute: "0"

- name: Restart cron service
  ansible.builtin.service:
    name: "{{ 'crond' if ansible_facts['os_family'] == 'RedHat' else 'cron' }}"
    state: restarted
    enabled: true
