# roles/scheduled_reboot/defaults/main.yml
---
# Default schedule: Thursday at 00:00 (Midnight)
# OnCalendar format: https://www.freedesktop.org/software/systemd/man/systemd.time.html
scheduled_reboot_timer_calendar: "Thu *-*-* 00:00:00"

scheduled_reboot_script_name: "scheduled_reboot"
