---
- name: Set nebula-sync project directory
  set_fact:
    nebula_sync_project_dir: "/home/{{ template.user }}/nebula-sync"

- name: Create a directory for nebula-sync
  file:
    path: "{{ nebula_sync_project_dir }}"
    state: directory
    mode: "0755"

- name: Create docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ nebula_sync_project_dir }}/docker-compose.yml"
    mode: "0644"

- name: Pull the latest image and start the nebula-sync service
  community.docker.docker_compose_v2:
    project_src: "{{ nebula_sync_project_dir }}"
    state: present
    pull: always
    recreate: auto
