---
- name: Deploy the Pi-hole gravity update script
  ansible.builtin.template:
    src: pihole_gravity_update.sh.j2
    dest: "/usr/local/bin/{{ pihole_gravity_update_script_name }}.sh"
    owner: root
    group: root
    mode: "0755"

- name: Deploy systemd service unit
  ansible.builtin.template:
    src: pihole-gravity-update.service.j2
    dest: "/etc/systemd/system/pihole-gravity-update.service"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Deploy systemd timer unit
  ansible.builtin.template:
    src: pihole-gravity-update.timer.j2
    dest: "/etc/systemd/system/pihole-gravity-update.timer"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable and start Pi-hole gravity update timer
  ansible.builtin.systemd:
    name: pihole-gravity-update.timer
    enabled: true
    state: started
    daemon_reload: true
