---
promtail_version: "3.3.2"
promtail_loki_url: "http://{{ vms.loki.ip }}:3100/loki/api/v1/push"
promtail_port: 9080
promtail_install_dir: "/usr/local/bin"
promtail_config_dir: "/etc/promtail"
promtail_positions_file: "/var/lib/promtail/positions.yaml"
promtail_docker_installed: false
