---
- name: Restart pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted

- name: Restart network manager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Reboot server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for SELinux state change"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
