---
grafana_version: "latest"
grafana_http_port: 3000
grafana_data_dir: "/home/{{ template.user }}/grafana"
grafana_admin_user: "admin"
grafana_admin_password: "{{ grafana_admin_pass }}"
grafana_loki_url: "http://{{ vms.loki.ip }}:3100"
