---
- name: Deploy the Docker auto-update script
  ansible.builtin.template:
    src: docker_auto_update.sh.j2
    dest: "/usr/local/bin/{{ docker_auto_update_script_name }}.sh"
    owner: root
    group: root
    mode: "0755"

- name: Deploy systemd service unit
  ansible.builtin.template:
    src: docker-auto-update.service.j2
    dest: "/etc/systemd/system/docker-auto-update.service"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Deploy systemd timer unit
  ansible.builtin.template:
    src: docker-auto-update.timer.j2
    dest: "/etc/systemd/system/docker-auto-update.timer"
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable and start Docker auto-update timer
  ansible.builtin.systemd:
    name: docker-auto-update.timer
    enabled: true
    state: started
    daemon_reload: true
