---
- name: Ensure prerequisites are installed (yum-utils)
  ansible.builtin.dnf:
    name: yum-utils
    state: present
    update_cache: true

- name: Add Docker CE repository
  ansible.builtin.command:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
  changed_when: true

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started # Ensure the service is running
    enabled: true # Ensure the service starts on boot

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ template.user }}"
    groups: "{{ docker_group }}"
    append: true
