$ANSIBLE_VAULT;1.1;AES256
38376565393761386563626135336266356432333535333838653839386465656230366661663164
3131656663616135653365323434373263633365653535620a303365383231346466363363633130
35373938663863373632663238316266343533326133303562363139653565353430636633613539
3338626135313063300a663033383663646661353836376561656263383038383334363061656364
36626338313264353532663637656434326634663730653339396236616165303139613461626332
3632383137623833393936383163343939386535666165336465
