$ANSIBLE_VAULT;1.1;AES256
38346535623332323036363530316131333831306535303638306261633934653666626239623863
3630306637326361373561376463653636333130393266340a643465326463356261646534616331
64616131306161303539333766353963633331376436376331393536653764663536623662376330
6334313438336362340a343764343732663662383863373432646530396438343066326431643362
31393636376166346230626533313762396365346462646338613434313234343639356561303037
3262616233383064316165343131643464313730396231626233
