$ANSIBLE_VAULT;1.1;AES256
38303734633236373465663363666662343537343061343562353961353264333764363431643462
6238333035613937313363353632383333613836623661300a373539393165386133393839373239
34353665346564666234353566363637343839313761383764313839626662343130326631356237
6362343664323163380a623738393639306239393066383538373439366132316433646162343965
34633861656434616261316333653632633331353039663139323866653933623032623861646137
3633336233376566323166643334653437633865303339363339
