---
- name: Configre backupserver
  hosts: backupserver
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    tailscale_node_hostname: backupserver
    scheduled_reboot_notify: false
  roles:
    - scheduled_update
    - scheduled_reboot
    - tailscale_node
