---
- name: Backup grafana before recreating VM
  hosts: grafana
  become: true
  gather_facts: false
  vars_files:
    - ../secrets.yml
  vars:
    grafana_data_dir: "/home/{{ template.user }}/grafana"
  tasks:
    - name: Take backup of current grafana
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../roles/grafana/tasks/backup.yml"
      when: force_recreate | default(false) | bool

- name: Create grafana VM
  hosts: proxmox
  become: false
  vars_files:
    - ../secrets.yml
  roles:
    - role: create_vm
      vars:
        create_vm_name: grafana
        create_vm_newid: "{{ vms.grafana.vmid }}"
        create_vm_ipaddr: "{{ vms.grafana.ip }}"
        create_vm_balloon: 1501
        create_vm_cores: 2
        create_vm_memory: 4096
        create_vm_sockets: 1
        create_vm_disk_size: 20G
        create_vm_virtiofs_tag: "{{ virtiofs_tags.smb }}"

- name: Configure grafana vm
  hosts: grafana
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    scheduled_reboot_notify: false
    docker_auto_update_compose_paths:
      - "/home/{{ template.user }}/grafana/docker-compose.yml"
  roles:
    - mount_virtiofs
    - firewall
    - docker
    - grafana
    - docker_auto_update
    - scheduled_reboot
    - scheduled_update
