---
- name: Create samba VM
  hosts: proxmox
  become: false
  vars_files:
    - ../secrets.yml
  roles:
    - role: create_vm
      vars:
        create_vm_name: samba
        create_vm_newid: 4004
        create_vm_ipaddr: "{{ vms.samba.ip }}"
        create_vm_balloon: 1501
        create_vm_cores: 1
        create_vm_memory: 3002
        create_vm_sockets: 1
        create_vm_disk_size: 10G
        create_vm_virtiofs_tag: "{{ virtiofs_tags.smb }}"

- name: Configure samba vm
  hosts: samba
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    scheduled_reboot_notify: false
  roles:
    - samba
    - scheduled_reboot
    - scheduled_update
