---
- name: Create samba VM
  hosts: proxmox
  become: false
  vars_files:
    - ../secrets.yml
  roles:
    - role: create_vm
      vars:
        name: samba
        newid: 4004
        ipaddr: "{{ vms.samba.ip }}"
        balloon: 1501
        cores: 1
        memory: 3002
        sockets: 1
        primary_disk_size: 10G

- name: Configure samba vm
  hosts: samba
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    send_reboot_pushover_notification: false
  roles:
    - samba
    - scheduled_reboot
    - scheduled_update
