---
- name: Create systemd service unit for ZFS key loading
  ansible.builtin.template:
    src: zfs-load-key.service.j2
    dest: /etc/systemd/system/zfs-load-key.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd daemon

- name: Enable the zfs-load-key service
  ansible.builtin.systemd:
    name: zfs-load-key.service
    enabled: yes